name: publish-staging

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump'
        required: true
        default: 'prerelease'
        type: choice
        options:
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: Update .npmrc
        run: |
          echo "@fafo-test-org:registry=https://npm.pkg.github.com" >> ~/.npmrc
        # Use staging environment packages for test
      - run: npm ci
      - run: npm test

  publish:
    needs: test # Don't publish without passing tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Setup Git
        run: git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Update .npmrc
        run: |
          echo "@fafo-test-org:registry=https://npm.pkg.github.com" >> ~/.npmrc
        # Use staging environment packages for staging deploy
      - run: npm ci
      - name: Bump version
        run: npm version --preid next ${{ inputs.version_bump }}
      - name: Push with tags
        run: git push --follow-tags
      - run: npm publish --tag next 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
